"""

Revision ID: 173bb1b573e6
Revises:
Create Date: 2026-02-19 15:19:51.273796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.db.types import GUID


# revision identifiers, used by Alembic.
revision: str = "173bb1b573e6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_config",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "learning_content",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "CRYPTO_BASICS",
                "AI_TRADING",
                "RISK_MANAGEMENT",
                "AUTOMATED_TRADING",
                "PLATFORM_GUIDE",
                name="content_category_enum",
            ),
            nullable=False,
        ),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("VIDEO", "ARTICLE", "PDF", name="content_type_enum"),
            nullable=False,
        ),
        sa.Column("content_url", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plans",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("price_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "billing_cycle",
            sa.Enum("MONTHLY", "QUARTERLY", "YEARLY", name="billing_cycle_enum"),
            nullable=False,
        ),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("max_strategies", sa.Integer(), nullable=False),
        sa.Column("max_allocation", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("ate_access", sa.Boolean(), nullable=False),
        sa.Column("trial_days", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ARCHIVED", name="plan_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("wallet_address_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "wallet_type",
            sa.Enum("CONNECTED", "GENERATED", name="wallet_type_enum"),
            nullable=True,
        ),
        sa.Column("encrypted_private_key", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column(
            "email_verified", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("email_verification_code", sa.String(length=6), nullable=True),
        sa.Column(
            "email_verification_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("telegram_bot_token", sa.String(length=255), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("notification_preferences", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_wallet_address_hash"),
        "users",
        ["wallet_address_hash"],
        unique=True,
    )
    op.create_table(
        "ambassadors",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column(
            "rank",
            sa.Enum(
                "BRONZE",
                "SILVER",
                "GOLD",
                "PLATINUM",
                "DIAMOND",
                name="ambassador_rank_enum",
            ),
            nullable=False,
        ),
        sa.Column("referral_code", sa.String(length=20), nullable=False),
        sa.Column("referred_by", GUID(length=36), nullable=True),
        sa.Column("team_size", sa.Integer(), nullable=False),
        sa.Column("total_referrals", sa.Integer(), nullable=False),
        sa.Column("rewards_earned", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referred_by"], ["ambassadors.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referral_code"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.String(length=100), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_logs_user_id_created_at",
        "audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "strategies",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "strategy_type",
            sa.Enum(
                "CONSERVATIVE",
                "MODERATE",
                "AGGRESSIVE",
                "CUSTOM",
                name="strategy_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "risk_profile",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="risk_profile_enum"),
            nullable=False,
        ),
        sa.Column("leverage_limit", sa.Float(), nullable=False),
        sa.Column("max_positions", sa.Integer(), nullable=False),
        sa.Column(
            "capital_allocation", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column("max_drawdown_percent", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategies_user_id"), "strategies", ["user_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column("plan_id", GUID(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "INACTIVE",
                "PENDING_PAYMENT",
                "ACTIVE",
                "EXPIRING_SOON",
                "EXPIRED",
                "CANCELLED",
                name="subscription_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("grace_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nowpayments_invoice_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_subscriptions_user_status",
        "subscriptions",
        ["user_id", "status"],
        unique=False,
    )
    op.create_table(
        "support_tickets",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED", name="ticket_status_enum"
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", "URGENT", name="ticket_priority_enum"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_support_tickets_user_id"), "support_tickets", ["user_id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "DEPOSIT",
                "EXECUTION",
                "SUBSCRIPTION",
                "REWARD",
                name="transaction_category_enum",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("wallet_address_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "FAILED", name="transaction_status_enum"),
            nullable=False,
        ),
        sa.Column("verification_link", sa.Text(), nullable=True),
        sa.Column("tx_hash", sa.String(length=66), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("subscription_id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("amount_crypto", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("crypto_currency", sa.String(length=10), nullable=True),
        sa.Column("nowpayments_payment_id", sa.String(length=100), nullable=True),
        sa.Column("nowpayments_invoice_id", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "CONFIRMING",
                "CONFIRMED",
                "SENDING",
                "PARTIALLY_PAID",
                "FINISHED",
                "FAILED",
                "REFUNDED",
                "EXPIRED",
                name="payment_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nowpayments_payment_id"),
    )
    op.create_index(
        op.f("ix_payments_subscription_id"),
        "payments",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "signals",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("strategy_id", GUID(length=36), nullable=True),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("BUY", "SELL", "HOLD", name="signal_direction_enum"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("take_profit", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("risk_reward_ratio", sa.Float(), nullable=True),
        sa.Column("indicators", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "EXECUTING",
                "FILLED",
                "EXPIRED",
                "CANCELLED",
                name="signal_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_responses", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signals_status_created", "signals", ["status", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_signals_strategy_id"), "signals", ["strategy_id"], unique=False
    )
    op.create_index(op.f("ix_signals_symbol"), "signals", ["symbol"], unique=False)
    op.create_table(
        "support_messages",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("ticket_id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["support_tickets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_support_messages_ticket_id"),
        "support_messages",
        ["ticket_id"],
        unique=False,
    )
    op.create_table(
        "executions",
        sa.Column("id", GUID(length=36), nullable=False),
        sa.Column("signal_id", GUID(length=36), nullable=False),
        sa.Column("user_id", GUID(length=36), nullable=False),
        sa.Column("strategy_id", GUID(length=36), nullable=False),
        sa.Column("wallet_address_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "order_type",
            sa.Enum("MARKET", "LIMIT", name="order_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum("BUY", "SELL", "HOLD", name="signal_direction_enum"),
            nullable=False,
        ),
        sa.Column("entry_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("leverage", sa.Float(), nullable=False),
        sa.Column("pnl", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("tx_hash", sa.String(length=66), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "FILLED",
                "PARTIALLY_FILLED",
                "CLOSED",
                "CANCELLED",
                "FAILED",
                name="execution_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["signal_id"], ["signals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_executions_signal_id"), "executions", ["signal_id"], unique=False
    )
    op.create_index(
        op.f("ix_executions_strategy_id"), "executions", ["strategy_id"], unique=False
    )
    op.create_index(
        op.f("ix_executions_user_id"), "executions", ["user_id"], unique=False
    )
    op.create_index(
        "ix_executions_user_status", "executions", ["user_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_executions_user_status", table_name="executions")
    op.drop_index(op.f("ix_executions_user_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_strategy_id"), table_name="executions")
    op.drop_index(op.f("ix_executions_signal_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(op.f("ix_support_messages_ticket_id"), table_name="support_messages")
    op.drop_table("support_messages")
    op.drop_index(op.f("ix_signals_symbol"), table_name="signals")
    op.drop_index(op.f("ix_signals_strategy_id"), table_name="signals")
    op.drop_index("ix_signals_status_created", table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_payments_subscription_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_support_tickets_user_id"), table_name="support_tickets")
    op.drop_table("support_tickets")
    op.drop_index("ix_subscriptions_user_status", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_strategies_user_id"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_index("ix_audit_logs_user_id_created_at", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("ambassadors")
    op.drop_index(op.f("ix_users_wallet_address_hash"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("plans")
    op.drop_table("learning_content")
    op.drop_table("admin_config")
    # ### end Alembic commands ###
