"""add ambassador team_size fields

Revision ID: 2d303c8cd0b5
Revises: f2g3h4i5j6k7
Create Date: 2026-05-13 23:33:41.721604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d303c8cd0b5"
down_revision: Union[str, None] = "f2g3h4i5j6k7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ambassador_bonuses",
        "bonus_type",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum(
            "rank_advancement",
            "performance_milestone",
            "fast_start",
            "loyalty_retention",
            "leadership_pool",
            "generational_override",
            name="bonus_type_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "ambassador_bonuses",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "ambassador_commissions",
        "active_referral_count",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "ambassador_commissions",
        "commission_amount",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "ambassador_commissions",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.drop_column("ambassador_commissions", "commission_rate")
    op.alter_column(
        "ambassador_payouts",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "pending",
            "processing",
            "paid",
            "failed",
            name="payout_status_enum",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "ambassador_territories",
        "territory_type",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "geographic",
            "demographic",
            "platform",
            name="territory_type_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "ambassador_travel_incentives",
        "rank_required",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.Enum(
            "associate",
            "bronze_leader",
            "silver_leader",
            "gold_leader",
            "platinum_leader",
            "diamond_leader",
            "elite_diamond",
            "black_diamond",
            "crown_ambassador",
            "grand_crown",
            name="ambassador_rank_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "ambassador_travel_incentives",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "qualifying",
            "qualified",
            "awarded",
            "expired",
            name="travel_status_enum",
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'qualifying'::character varying"),
    )
    op.execute(
        "UPDATE binance_signals SET updated_at = created_at WHERE updated_at IS NULL"
    )
    op.alter_column(
        "binance_signals",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.execute(
        "UPDATE bybit_signals SET updated_at = created_at WHERE updated_at IS NULL"
    )
    op.alter_column(
        "bybit_signals",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "leadership_revenue_pools",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_user_id"),
        "portfolio_snapshots",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "territory_commissions",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "territory_commissions",
        "status",
        existing_type=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.drop_index(
        op.f("ix_portfolio_snapshots_user_id"), table_name="portfolio_snapshots"
    )
    op.alter_column(
        "leadership_revenue_pools",
        "status",
        existing_type=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "bybit_signals",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "binance_signals",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.alter_column(
        "ambassador_travel_incentives",
        "status",
        existing_type=sa.Enum(
            "qualifying",
            "qualified",
            "awarded",
            "expired",
            name="travel_status_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'qualifying'::character varying"),
    )
    op.alter_column(
        "ambassador_travel_incentives",
        "rank_required",
        existing_type=sa.Enum(
            "associate",
            "bronze_leader",
            "silver_leader",
            "gold_leader",
            "platinum_leader",
            "diamond_leader",
            "elite_diamond",
            "black_diamond",
            "crown_ambassador",
            "grand_crown",
            name="ambassador_rank_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "ambassador_territories",
        "territory_type",
        existing_type=sa.Enum(
            "geographic",
            "demographic",
            "platform",
            name="territory_type_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "ambassador_payouts",
        "status",
        existing_type=sa.Enum(
            "pending",
            "processing",
            "paid",
            "failed",
            name="payout_status_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.add_column(
        "ambassador_commissions",
        sa.Column(
            "commission_rate",
            sa.NUMERIC(precision=5, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "ambassador_commissions",
        "status",
        existing_type=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "ambassador_commissions",
        "commission_amount",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        nullable=True,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.alter_column(
        "ambassador_commissions",
        "active_referral_count",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "ambassador_bonuses",
        "status",
        existing_type=sa.Enum(
            "pending", "paid", name="commission_status_enum", native_enum=False
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "ambassador_bonuses",
        "bonus_type",
        existing_type=sa.Enum(
            "rank_advancement",
            "performance_milestone",
            "fast_start",
            "loyalty_retention",
            "leadership_pool",
            "generational_override",
            name="bonus_type_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
